### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by kazem3d** [tomickigrzegorz/react-leaflet-examples#17]
the links are broken an 404 error

**Comment by tomickigrzegorz** [comment]
Could you be more specific which link?

**Comment by kazem3d** [comment]
https://tomik23.github.io/react-leaflet-examples/

**Comment by tomickigrzegorz** [comment]
Thanks I changed my username and had to correct everywhere in all projects. As you can see, I didn't find it everywhere :)
